const fs = require('fs');

const p = '/app/packages/twenty-server/dist/engine/core-modules/workspace-invitation/services/workspace-invitation.service.js';
let c = fs.readFileSync(p, 'utf8');

// Replace any Twenty references in message objects
c = c.replace(/message:\s*"Join your team on Twenty"/g, 'message: "You\'ve been invited to join Zed Agency CRM"');
c = c.replace(/message:\s*"Join your team on Zed"/g, 'message: "You\'ve been invited to join Zed Agency CRM"');
c = c.replace(/\(via Twenty\)/g, '(via Zed Agency)');
c = c.replace(/Twenty CRM/gi, 'Zed Agency CRM');

// Replace the subject line with clean high-deliverability subject
c = c.replace(
  /const subject = i18n\._\(joinTeamMsg\);/g,
  'const subject = "Invitation to join " + (workspace.displayName || "Zed Agency Workspace") + " on Zed Agency CRM";'
);

// Inject 1-to-1 White Luxury HTML template matching user mock
const startMarker = 'const inviterName = [sender.name?.firstName';
const endMarker = '</html>`;';
const startIdx = c.indexOf(startMarker);

if (startIdx !== -1) {
  const endIdx = c.indexOf(endMarker, startIdx);
  if (endIdx !== -1) {
    const luxuryCode = [
      "const inviterName = [sender.name?.firstName, sender.name?.lastName].filter(Boolean).join(' ') || sender.userEmail || 'Zed Admin';",
      "const workspaceTitle = workspace.displayName || 'Zed Agency Workspace';",
      "const inviteUrl = link.toString();",
      "const isRoleAdmin = (invitation.value.appToken?.context?.roleId === '333b18a3-f026-4608-ba6b-0fc0c0adda87') || (roleId === '333b18a3-f026-4608-ba6b-0fc0c0adda87');",
      "const roleTitle = isRoleAdmin ? 'Administrator' : 'Team Member';",
      "const roleUpper = isRoleAdmin ? 'ADMINISTRATOR' : 'TEAM MEMBER';",
      "const roleDesc = isRoleAdmin",
      "  ? 'You will have full administrative authority over workspace settings, security, integrations, client databases, and team management.'",
      "  : 'You will have collaborative access to the lead discovery tool, client communication channels, AI assistant, and smart tasks pipeline.';",
      "const html = `<!DOCTYPE html>",
      "<html lang=\"en\">",
      "<head>",
      "  <meta charset=\"utf-8\">",
      "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
      "  <title>You've been invited to join ${workspaceTitle}</title>",
      "</head>",
      "<body style=\"margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; color: #000000;\">",
      "  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color: #f8fafc; padding: 40px 16px;\">",
      "    <tr>",
      "      <td align=\"center\">",
      "        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width: 580px; background-color: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 10px 30px rgba(0,0,0,0.04); padding: 40px;\">",
      "          <!-- Header -->",
      "          <tr>",
      "            <td>",
      "              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">",
      "                <tr>",
      "                  <td style=\"vertical-align: middle;\">",
      "                    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">",
      "                      <tr>",
      "                        <td style=\"background-color: #000000; width: 44px; height: 44px; border-radius: 10px; text-align: center; vertical-align: middle;\">",
      "                          <!-- Official White Z Logo Symbol -->",
      "                          <div style=\"color: #ffffff; font-family: -apple-system, sans-serif; font-size: 26px; font-weight: 900; line-height: 44px; text-align: center;\">Z</div>",
      "                        </td>",
      "                        <td style=\"padding-left: 14px; vertical-align: middle;\">",
      "                          <div style=\"color: #000000; font-size: 20px; font-weight: 800; letter-spacing: -0.4px; line-height: 1.2;\">Zed Agency</div>",
      "                          <div style=\"color: #64748b; font-size: 13px; font-weight: 500; margin-top: 2px;\">Enterprise Growth. AI CRM Platform.</div>",
      "                        </td>",
      "                      </tr>",
      "                    </table>",
      "                  </td>",
      "                  <td align=\"right\" style=\"vertical-align: middle;\">",
      "                    <span style=\"color: #000000; font-size: 12px; font-weight: 800; letter-spacing: 0.8px; text-transform: uppercase;\">OFFICIAL INVITATION</span>",
      "                  </td>",
      "                </tr>",
      "              </table>",
      "            </td>",
      "          </tr>",
      "          <!-- Divider -->",
      "          <tr>",
      "            <td style=\"padding: 24px 0 32px 0;\">",
      "              <div style=\"border-bottom: 1px solid #e2e8f0; height: 1px; width: 100%;\"></div>",
      "            </td>",
      "          </tr>",
      "          <!-- Headline & Salutation -->",
      "          <tr>",
      "            <td>",
      "              <h1 style=\"margin: 0 0 20px 0; font-size: 24px; font-weight: 800; color: #000000; letter-spacing: -0.4px;\">",
      "                You've been invited to join ${workspaceTitle}",
      "              </h1>",
      "              <p style=\"margin: 0 0 16px 0; font-size: 15px; line-height: 1.6; color: #334155;\">",
      "                Hello,",
      "              </p>",
      "              <p style=\"margin: 0 0 28px 0; font-size: 15px; line-height: 1.6; color: #334155;\">",
      "                <strong style=\"color: #000000;\">${inviterName}</strong> (<span style=\"color: #2563eb; text-decoration: underline;\">${sender.userEmail}</span>) has invited you to collaborate as an authorized <strong style=\"color: #000000;\">${roleTitle}</strong> on the <strong style=\"color: #000000;\">${workspaceTitle}</strong> workspace on Zed CRM.",
      "              </p>",
      "            </td>",
      "          </tr>",
      "          <!-- Position Card -->",
      "          <tr>",
      "            <td>",
      "              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color: #fafafa; border: 1px solid #e5e7eb; border-radius: 12px; padding: 24px; margin-bottom: 32px;\">",
      "                <tr>",
      "                  <td>",
      "                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">",
      "                      <tr>",
      "                        <td>",
      "                          <div style=\"font-size: 11px; font-weight: 800; color: #000000; text-transform: uppercase; letter-spacing: 0.8px; margin-bottom: 6px;\">YOUR ASSIGNED POSITION</div>",
      "                          <div style=\"font-size: 22px; font-weight: 800; color: #000000;\">${roleTitle}</div>",
      "                        </td>",
      "                        <td align=\"right\" style=\"vertical-align: middle;\">",
      "                          <span style=\"color: #000000; font-size: 12px; font-weight: 800; letter-spacing: 0.5px;\">👤 | ${roleUpper}</span>",
      "                        </td>",
      "                      </tr>",
      "                    </table>",
      "                    <p style=\"margin: 16px 0 20px 0; font-size: 14px; line-height: 1.6; color: #4b5563;\">",
      "                      ${roleDesc}",
      "                    </p>",
      "                    <div style=\"border-top: 1px solid #e5e7eb; padding-top: 16px;\">",
      "                      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">",
      "                        <tr>",
      "                          <td style=\"font-size: 14px; font-weight: 700; color: #000000; padding: 4px 0;\">",
      "                            ✓ Lead Scraper &amp; Finder &nbsp;&nbsp;&nbsp;&nbsp; ✓ Client Pipelines",
      "                          </td>",
      "                        </tr>",
      "                        <tr>",
      "                          <td style=\"font-size: 14px; font-weight: 700; color: #000000; padding: 4px 0;\">",
      "                            ✓ AI Assistant",
      "                          </td>",
      "                        </tr>",
      "                      </table>",
      "                    </div>",
      "                  </td>",
      "                </tr>",
      "              </table>",
      "            </td>",
      "          </tr>",
      "          <!-- Primary Black CTA Button with Z Symbol -->",
      "          <tr>",
      "            <td align=\"center\" style=\"padding-bottom: 32px;\">",
      "              <a href=\"${inviteUrl}\" target=\"_blank\" style=\"display: inline-block; background-color: #000000; color: #ffffff; font-size: 15px; font-weight: 700; text-decoration: none; padding: 16px 36px; border-radius: 10px; text-align: center; box-shadow: 0 4px 12px rgba(0,0,0,0.15);\">",
      "                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"display: inline-table; vertical-align: middle;\">",
      "                  <tr>",
      "                    <td style=\"padding-right: 12px; vertical-align: middle;\">",
      "                      <div style=\"color: #ffffff; font-family: -apple-system, sans-serif; font-size: 18px; font-weight: 900; line-height: 1;\">Z</div>",
      "                    </td>",
      "                    <td style=\"color: #ffffff; font-size: 15px; font-weight: 700; vertical-align: middle;\">",
      "                      Accept Invitation &amp; Join as ${roleTitle} &rarr;",
      "                    </td>",
      "                  </tr>",
      "                </table>",
      "              </a>",
      "            </td>",
      "          </tr>",
      "          <!-- Fallback URL Card -->",
      "          <tr>",
      "            <td>",
      "              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color: #ffffff; border: 1px solid #e5e7eb; border-radius: 10px; padding: 18px 20px; margin-bottom: 24px;\">",
      "                <tr>",
      "                  <td>",
      "                    <p style=\"margin: 0 0 8px 0; font-size: 13px; font-weight: 600; color: #374151;\">",
      "                      If the button above does not open, copy and paste this link in your browser:",
      "                    </p>",
      "                    <p style=\"margin: 0; font-size: 13px; line-height: 1.5; color: #2563eb; word-break: break-all; text-decoration: underline;\">",
      "                      ${inviteUrl}",
      "                    </p>",
      "                  </td>",
      "                </tr>",
      "              </table>",
      "            </td>",
      "          </tr>",
      "          <!-- Security Notice with Lock Icon -->",
      "          <tr>",
      "            <td style=\"padding-bottom: 32px;\">",
      "              <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">",
      "                <tr>",
      "                  <td style=\"background-color: #f3f4f6; width: 36px; height: 36px; border-radius: 50%; text-align: center; vertical-align: middle;\">",
      "                    <span style=\"font-size: 16px;\">🔒</span>",
      "                  </td>",
      "                  <td style=\"padding-left: 14px; font-size: 13px; line-height: 1.5; color: #4b5563;\">",
      "                    <strong style=\"color: #111827;\">Security is Priority:</strong><br/>",
      "                    This official invitation link was generated specifically for you and will expire in 7 days. After accepting, you can sign in directly using your Google account.",
      "                  </td>",
      "                </tr>",
      "              </table>",
      "            </td>",
      "          </tr>",
      "          <!-- Footer -->",
      "          <tr>",
      "            <td>",
      "              <div style=\"border-top: 1px solid #e5e7eb; padding-top: 24px; text-align: center;\">",
      "                <p style=\"margin: 0 0 6px 0; font-size: 13px; font-weight: 600; color: #374151;\">",
      "                  Dispatched securely by <strong style=\"color: #000000;\">Zed Agency Enterprise CRM</strong>",
      "                </p>",
      "                <p style=\"margin: 0; font-size: 12px; color: #6b7280;\">",
      "                  &copy; 2025 Zed Agency Technologies. All rights reserved.",
      "                </p>",
      "              </div>",
      "            </td>",
      "          </tr>",
      "        </table>",
      "      </td>",
      "    </tr>",
      "  </table>",
      "</body>",
      "</html>`;"
    ].join('\n');
    c = c.substring(0, startIdx) + luxuryCode + c.substring(endIdx + endMarker.length);
  }
}

fs.writeFileSync(p, c, 'utf8');
console.log('✅ workspace-invitation.service.js successfully updated with exact White Luxury Zed mockup!');
